### ISSUE TITLE
Algorithm comparison tool is throwing an exception related to Parameters.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1134]
Oh shoot, the algorithm comparison tool still has a bug that's preventing it from outputting any statistics. This exception, when I run the default ExampleCompareSimulation.java. 'AP' is one of the statistics configured in the file. Maybe those statistics are no longer getting into the Parameters object... let me look real quick. This a bug Bryan found yesterday, as I recall.
 
Exception in thread "main" java.lang.IllegalArgumentException: A description of 'AP' has not been given in ParamDescriptions.
at edu.cmu.tetrad.util.Parameters.getValues(Parameters.java:222)
at edu.cmu.tetrad.algcomparison.Comparison.printStats(Comparison.java:1585)
at edu.cmu.tetrad.algcomparison.Comparison.compareFromSimulations(Comparison.java:419)
at edu.cmu.tetrad.algcomparison.Comparison.compareFromSimulations(Comparison.java:185)
at edu.cmu.tetrad.algcomparison.examples.ExampleCompareSimulation.main(ExampleCompareSimulation.java:86)

**Comment by jdramsey** [comment]
Actually, it works if you just comment out the lines 1583 - 1590 in Comparison.java. Given that it still works, I'm not sure what those lines were ever for...

                    if (simulation instanceof HasParameterValues) {
                        parameters.putAll(((HasParameterValues) simulation).getParameterValues());
                    }

//                    final String abbreviation = statistic.getAbbreviation();
//
//                    Object[] o = parameters.getValues(abbreviation);
//
//                    if (o.length == 1 && o[0] instanceof String) {
//                        table.setToken(t + 1, initialColumn + statIndex, (String) o[0]);
//                        continue;
//                    }

                    double stat = statTables[u][newOrder[t]][statIndex];

**Comment by jdramsey** [comment]
This is fixed.
