### ISSUE TITLE
FasConcurrent doesn't work on Rfci with a bootstrapping option

### ISSUE THREAD

**Issue by chirayukong** [cmu-phil/tetrad#1190]
@jdramsey 
java.lang.IllegalArgumentException
	at edu.cmu.tetrad.search.IndTestScore.isIndependent(IndTestScore.java:91)
	at edu.cmu.tetrad.search.FasConcurrent.doNodeDepth0(FasConcurrent.java:385)
	at edu.cmu.tetrad.search.FasConcurrent.access$1(FasConcurrent.java:353)
	at edu.cmu.tetrad.search.FasConcurrent$1Depth0Task.call(FasConcurrent.java:217)
	at edu.cmu.tetrad.search.FasConcurrent$1Depth0Task.call(FasConcurrent.java:1)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by jdramsey** [comment]
It looks like fans is being run using a score. Have you tried fisher z instead?

**Comment by jdramsey** [comment]
It looks like fans is being run using a score. Have you tried fisher z instead?

**Comment by jdramsey** [comment]
It looks like fans is being run using a score. Have you tried fisher z instead?

**Comment by chirayukong** [comment]
But the dataset is discrete, so I ran it with Chi Square test, the default one. I'll try to debug it myself.

**Comment by chirayukong** [comment]
Nevermind. My code is out of date. It works. Sorry about that.
