### ISSUE TITLE
No output when using FCI/ KCI

### ISSUE THREAD

**Issue by szdata** [cmu-phil/tetrad#1244]
Output message on Ubuntu with OpenJDK 1.8

C15 --- C17 because it was forbidden by background knowledge.
C15 --- C18 because it was forbidden by background knowledge.
C18 --- C19 because it was forbidden by background knowledge.
java.lang.NullPointerException
	at edu.cmu.tetrad.search.IndTestConditionalCorrelation.isIndependent(IndTestConditionalCorrelation.java:135)
	at edu.cmu.tetrad.search.SepsetsSet.isIndependent(SepsetsSet.java:64)
	at edu.cmu.tetrad.search.SepsetsSet.isCollider(SepsetsSet.java:51)
	at edu.cmu.tetrad.search.FciOrient.ruleR0(FciOrient.java:219)
	at edu.cmu.tetrad.search.Fci.search(Fci.java:212)
	at edu.cmu.tetrad.search.Fci.search(Fci.java:186)
	at edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.Fci.search(Fci.java:68)
	at edu.cmu.tetradapp.model.GeneralAlgorithmRunner.lambda$execute$2(GeneralAlgorithmRunner.java:319)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at edu.cmu.tetradapp.model.GeneralAlgorithmRunner.execute(GeneralAlgorithmRunner.java:305)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor$1.watch(GeneralAlgorithmEditor.java:1084)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Thread-35" java.lang.NullPointerException
	at edu.cmu.tetrad.search.IndTestConditionalCorrelation.isIndependent(IndTestConditionalCorrelation.java:135)
	at edu.cmu.tetrad.search.SepsetsSet.isIndependent(SepsetsSet.java:64)
	at edu.cmu.tetrad.search.SepsetsSet.isCollider(SepsetsSet.java:51)
	at edu.cmu.tetrad.search.FciOrient.ruleR0(FciOrient.java:219)
	at edu.cmu.tetrad.search.Fci.search(Fci.java:212)
	at edu.cmu.tetrad.search.Fci.search(Fci.java:186)
	at edu.cmu.tetrad.algcomparison.algorithm.oracle.pag.Fci.search(Fci.java:68)
	at edu.cmu.tetradapp.model.GeneralAlgorithmRunner.lambda$execute$2(GeneralAlgorithmRunner.java:319)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at edu.cmu.tetradapp.model.GeneralAlgorithmRunner.execute(GeneralAlgorithmRunner.java:305)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor$1.watch(GeneralAlgorithmEditor.java:1084)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jdramsey** [comment]
Interesting. Here's what that line says:

List<String> _z = new ArrayList<>();
for (Node node : z) _z.add(node.getName());

So here _z can't be null (it was just set to a new ArrayList), so either it must be the case that z is null or that z contains a null pointer.

Oh wait, maybe it's an error in SepsetMap, here, line 56

    private boolean returnEmptyIfNotSet = false;

Do you have access to the code? Can you set that to true?

**Comment by jdramsey** [comment]
Now why you're having this problem and I'm not is also an interesting question. The difference there may simply be an incompatibility between OPEN JDK and Oracle's JDK.

**Comment by jdramsey** [comment]
Were you able to set that? I can make a build for you if you like.

**Comment by szdata** [comment]
Thanks for the suggestion. I tried JDK 11.05 and it works! We didn't try JDK before because I experienced a similar problem on Win10 + JDK12.01.

**Comment by szdata** [comment]
> 
> 
> Were you able to set that? I can make a build for you if you like.

Thanks for the suggestion. I tried JDK 11.05 and it works! We didn't try JDK before because I experienced a similar problem on Win10 + JDK12.01.

> 
> 
> Now why you're having this problem and I'm not is also an interesting question. The difference there may simply be an incompatibility between OPEN JDK and Oracle's JDK.

Thanks for the suggestion. I tried JDK 11.05 and it works! We didn't try JDK before because I experienced a similar problem on Win10 + JDK12.01.

**Comment by szdata** [comment]
Thanks for the suggestion. I tried JDK 11.05 and it works! We didn't try JDK before because I experienced a similar problem on Win10 + JDK12.01.

> 
> 
> Now why you're having this problem and I'm not is also an interesting question. The difference there may simply be an incompatibility between OPEN JDK and Oracle's JDK.

**Comment by jdramsey** [comment]
That's good to know! In the back of my mind, I'd like to convince the team to move to Open JDK, but that may take a while. Good to know this works!
