### ISSUE TITLE
FGS: Null Pointer Exception

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#132]
I got the following error when running FGS on dataset containing 407 cases and 20502 variables:

Exception in thread "main" java.lang.NullPointerException: First node must not be null.
	at edu.cmu.tetrad.graph.OrderedPair.<init>(OrderedPair.java:49)
	at edu.cmu.tetrad.search.Fgs.reevaluateForward(Fgs.java:783)
	at edu.cmu.tetrad.search.Fgs.fes(Fgs.java:666)
	at edu.cmu.tetrad.search.Fgs.search(Fgs.java:258)
	at edu.cmu.tetrad.cli.search.FgsCli.main(FgsCli.java:156)

This dataset has linear dependencies; However, the flag to ignore linear dependence was set.

**Comment by kvb2univpitt** [comment]
Solved!  Non-unique variable names cause this NullPointerException.

**Comment by jdramsey** [comment]
Great, thanks!

Joe

On Tue, May 17, 2016 at 11:05 PM, Kevin Bui <notifications@github.com>
wrote:

> Closed #132 <https://github.com/cmu-phil/tetrad/issues/132>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cmu-phil/tetrad/issues/132#event-663866734>
>



-- 
Joseph D. Ramsey
Special Faculty and Director of Research Computing
Department of Philosophy
135 Baker Hall
Carnegie Mellon University
Pittsburgh, PA 15213

jsph.ramsey@gmail.com
Office: (412) 268-8063
http://www.andrew.cmu.edu/user/jdramsey
