### ISSUE TITLE
Cannot load metadata 

### ISSUE THREAD

**Issue by mdibiase1** [cmu-phil/tetrad#1334]
Hi there,

I am using tetrad-gui-6.9.0-launch.jar with java version/build as follows:

java 16.0.2 2021-07-20
Java(TM) SE Runtime Environment (build 16.0.2+7-67)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

I am attempting to load a dataset containing 1780 cases and 10 variables with corresponding metadata. I am able to load in  data without metadata. However, when I try to load data with metadata (by loading a .json file), the GUI freezes on the 'validation' screen. I also tried using causal-cmd. Similar to the GUI, I am able to load data without metadata. When I add the --metadata flag, the anticipated output fges_*.txt is incomplete (see attached). I have also included the output printed to terminal. I require metadata as the default variable types will be incorrect in my case (I have ordinal variables with <5 unique values and categorical variables with >5 categories).  

**My .json file looks like this:**
{
"domains": [
{
"name": "alcohol_type_all_0",
"discrete": true
},
"name": "alcohol_intake_scale_0",
"discrete": false
},
"name": "alcohol_intake_frequency_0",
"discrete": false
u}
]
}

**causal-cmd command**
java -jar causal-cmd-1.3.0-jar-with-dependencies.jar --dataset Tetrad_brain_alcohol_vars.csv --algorithm fges --data-type continuous --delimiter comma --score sem-bic-score --knowledge knowledge_test_alcohol.txt --metadata tetrad_alcohol_vars.json 

**causal-cmd output**
[fges_1630370905745.txt](https://github.com/cmu-phil/tetrad/files/7080346/fges_1630370905745.txt)
Running version 1.3.0 but unable to contact latest version server.  To disable checking use the skip-latest option.
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `edu.pitt.dbmi.data.reader.metadata.ColumnMetadata` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('name')
 at [Source: (BufferedReader); line: 7, column: 1] (through reference chain: edu.pitt.dbmi.data.reader.metadata.Metadata["domains"]->java.util.ArrayList[1])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1588)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1213)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1495)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:207)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:197)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3561)
	at edu.pitt.dbmi.data.reader.metadata.MetadataFileReader.read(MetadataFileReader.java:44)
	at edu.pitt.dbmi.causal.cmd.data.DataFiles.readInMetadata(DataFiles.java:72)
	at edu.pitt.dbmi.causal.cmd.data.DataFiles.readInTabularData(DataFiles.java:110)
	at edu.pitt.dbmi.causal.cmd.data.DataFiles.readInDatasets(DataFiles.java:100)
	at edu.pitt.dbmi.causal.cmd.tetrad.TetradRunner.runAlgorithm(TetradRunner.java:74)
	at edu.pitt.dbmi.causal.cmd.CausalCmdApplication.runTetrad(CausalCmdApplication.java:133)
	at edu.pitt.dbmi.causal.cmd.CausalCmdApplication.main(CausalCmdApplication.java:105)

Your help would be greatly appreciated.

Thank you kindly,

Maria

**Comment by cg09** [comment]
I may be wrong, but I think the software ignores ordering of finite range
ordinal variables. If so, your metadata will be of no use.

**Comment by kvb2univpitt** [comment]
Your json file format is not correct.  You've got an extra "u" in there and you're missing two "{" before the "name" attributes.  Please try this:

```json
{
    "domains": [
        {
            "name": "alcohol_type_all_0",
            "discrete": true
        }, {
            "name": "alcohol_intake_scale_0",
            "discrete": false
        },
        {
            "name": "alcohol_intake_frequency_0",
            "discrete": false
        }
    ]
}
```

**Comment by mdibiase1** [comment]
Perfect! 

Thank you so much!

Maria

**Comment by jdramsey** [comment]
@kvb2univpitt Can we close this? I did notice hanging if the first (index) variable has no name--is that related?

**Comment by mdibiase1** [comment]
> @kvb2univpitt Can we close this? I did notice hanging if the first (index) variable has no name--is that related?

Yes - happy for you to close this. Thanks

**Comment by jdramsey** [comment]
@mdibiase1 Thanks!
