### ISSUE TITLE
Data sets can't be loaded in a Data box using Windows 10 Oracle java 8-123.

### ISSUE THREAD

**Issue by jdramsey** [cmu-phil/tetrad#1377]
Debug stack:

Infer demiliter for file: abalone.continuous.txt                                                                                                                      Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;                                                          at edu.pitt.dbmi.data.reader.util.TextFileUtils.inferDelimiter(TextFileUtils.java:135)                                                                                at edu.cmu.tetradapp.editor.LoadDataSettings.getInferredDelimiter(LoadDataSettings.java:882)                                                                          at edu.cmu.tetradapp.editor.LoadDataSettings.basicSettings(LoadDataSettings.java:503)                                                                                 at edu.cmu.tetradapp.editor.LoadDataDialog.showDataLoaderDialog(LoadDataDialog.java:165)                                                                              at edu.cmu.tetradapp.editor.LoadDataAction.actionPerformed(LoadDataAction.java:91)                                                                                    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)                                                                                                     at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)                                                                                                 at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)                                                                                                 at javax.swing.DefaultButtonModel.setPressed(Unknown Source)                                                                                                          at javax.swing.AbstractButton.doClick(Unknown Source)                                                                                                                 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)                                                                                                     at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)                                                                                       at java.awt.Component.processMouseEvent(Unknown Source)                                                                                                               at javax.swing.JComponent.processMouseEvent(Unknown Source)                                                                                                           at java.awt.Component.processEvent(Unknown Source)                                                                                                                    at java.awt.Container.processEvent(Unknown Source)                                                                                                                    at java.awt.Component.dispatchEventImpl(Unknown Source)                                                                                                               at java.awt.Container.dispatchEventImpl(Unknown Source)                                                                                                               at java.awt.Component.dispatchEvent(Unknown Source)                                                                                                                   at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)                                                                                                  at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)                                                                                                   at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)                                                                                                       at java.awt.Container.dispatchEventImpl(Unknown Source)                                                                                                               at java.awt.Window.dispatchEventImpl(Unknown Source)                                                                                                                  at java.awt.Component.dispatchEvent(Unknown Source)                                                                                                                   at java.awt.EventQueue.dispatchEventImpl(Unknown Source)                                                                                                              at java.awt.EventQueue.access$500(Unknown Source)                                                                                                                     at java.awt.EventQueue$3.run(Unknown Source)                                                                                                                          at java.awt.EventQueue$3.run(Unknown Source)                                                                                                                          at java.security.AccessController.doPrivileged(Native Method)                                                                                                         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                                                                      at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                                                                      at java.awt.EventQueue$4.run(Unknown Source)                                                                                                                          at java.awt.EventQueue$4.run(Unknown Source)                                                                                                                          at java.security.AccessController.doPrivileged(Native Method)                                                                                                         at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)                                                                      at java.awt.EventQueue.dispatchEvent(Unknown Source)                                                                                                                  at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)                                                                                                at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)                                                                                                   at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)                                                                                                at java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                                                                            at java.awt.EventDispatchThread.pumpEvents(Unknown Source)                                                                                                            at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by jdramsey** [comment]
That was a debug stack from Mike Conrad on Windows. Ruben gets the same debug stack on a Mac:

config file: /config/prodConfig.xml

Infer demiliter for file: sim-01.Network1_amp.continuous.txt

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;

	at edu.pitt.dbmi.data.reader.util.TextFileUtils.inferDelimiter(TextFileUtils.java:135)

	at edu.cmu.tetradapp.editor.LoadDataSettings.getInferredDelimiter(LoadDataSettings.java:882)

	at edu.cmu.tetradapp.editor.LoadDataSettings.basicSettings(LoadDataSettings.java:503)

	at edu.cmu.tetradapp.editor.LoadDataDialog.showDataLoaderDialog(LoadDataDialog.java:165)

	at edu.cmu.tetradapp.editor.LoadDataAction.actionPerformed(LoadDataAction.java:91)

	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)

	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)

	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)

	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)

	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)

	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)

	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)

	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)

	at java.awt.Component.processMouseEvent(Component.java:6539)

	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)

	at java.awt.Component.processEvent(Component.java:6304)

	at java.awt.Container.processEvent(Container.java:2239)

	at java.awt.Component.dispatchEventImpl(Component.java:4889)

	at java.awt.Container.dispatchEventImpl(Container.java:2297)

	at java.awt.Component.dispatchEvent(Component.java:4711)

	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)

	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)

	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)

	at java.awt.Container.dispatchEventImpl(Container.java:2283)

	at java.awt.Window.dispatchEventImpl(Window.java:2746)

	at java.awt.Component.dispatchEvent(Component.java:4711)

	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)

	at java.awt.EventQueue.access$500(EventQueue.java:97)

	at java.awt.EventQueue$3.run(EventQueue.java:709)

	at java.awt.EventQueue$3.run(EventQueue.java:703)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)

	at java.awt.EventQueue$4.run(EventQueue.java:733)

	at java.awt.EventQueue$4.run(EventQueue.java:731)

	at java.security.AccessController.doPrivileged(Native Method)

	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)

	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)

	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)

	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)

	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)

	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)

	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)

	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jdramsey** [comment]
This was Ruben's JDK (that he had the data loading bug with):

openjdk version "1.8.0_192"

OpenJDK Runtime Environment (Zulu 8.33.0.1-macosx) (build 1.8.0_192-b01)

OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-macosx) (build 25.192-b01, mixed mode)

**Comment by kvb2univpitt** [comment]
The problem is because it was compiled with Java 9+ and then run with Java 8.  The implementation for the ByteBuffer in Java9+ breaks the compatibility with Java8.  Other people have the same problem https://jira.mongodb.org/browse/JAVA-2559.   I will fix the compatibility issue.  In the meantime, compile and run Tetrad using jdk 1.8 as a work-around.

**Comment by jdramsey** [comment]
Ah ha! I knew I was compiling it wrong! Thanks.

**Comment by jdramsey** [comment]
Actually, this problem has been resolved. It should work in 7.3.1-1. Closing.
