### ISSUE TITLE
beam-search version of FGES

### ISSUE THREAD

**Issue by lockmatrix** [cmu-phil/tetrad#1404]
I love FGES, 
while I think maybe [beam search](https://en.wikipedia.org/wiki/Beam_search) can find a better result than greedy search.

**Comment by jdramsey** [comment]
How would that work?

**Comment by jdramsey** [comment]
BTW I'm glad you're enjoying FGES!

You know, I had done a beam search version of another algorithm using p-values and tried using BIC optimization with it, and it worked OK, but FGES still beat it, so (as is usual for me) I just deleted it. :)

**Comment by cg09** [comment]
Beam searches have a long history, starting at least with Lisrel. Didn't
work well. Best first often fails because second best and then next best
are better, etc.

**Comment by jdramsey** [comment]
I forget what your data looks like, but we have a new algorithm called GRaSP. Have you tried it? It's a permutation-based algorithm and is very accurate. If the number of variables is not to huge it's doable.

**Comment by lockmatrix** [comment]
GRaSP failed on my dataset.
`java -jar causal-cmd-1.4.1-SNAPSHOT-jar-with-dependencies.jar --algorithm grasp --penaltyDiscount 5 --dataset tetrad_data_v2.temp.csv --data-type mixed --delimiter comma --test cg-lr-test --score cg-bic-score --numCategories 16 --verbose`

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at edu.cmu.tetrad.search.ConditionalGaussianLikelihood.likelihoodJoint(ConditionalGaussianLikelihood.java:267)
	at edu.cmu.tetrad.search.ConditionalGaussianLikelihood.getLikelihood(ConditionalGaussianLikelihood.java:222)
	at edu.cmu.tetrad.search.ConditionalGaussianScore.localScore(ConditionalGaussianScore.java:80)
	at edu.cmu.tetrad.search.TeyssierScorer.score(TeyssierScorer.java:637)
	at edu.cmu.tetrad.search.TeyssierScorer.getGrowShrinkScore(TeyssierScorer.java:692)
	at edu.cmu.tetrad.search.TeyssierScorer.getParentsInternal(TeyssierScorer.java:812)
	at edu.cmu.tetrad.search.TeyssierScorer.recalculate(TeyssierScorer.java:660)
	at edu.cmu.tetrad.search.TeyssierScorer.initializeScores(TeyssierScorer.java:605)
	at edu.cmu.tetrad.search.TeyssierScorer.score(TeyssierScorer.java:125)
	at edu.cmu.tetrad.search.Grasp.bestOrder(Grasp.java:84)
	at edu.cmu.tetrad.algcomparison.algorithm.oracle.cpdag.GRaSP.search(GRaSP.java:83)
	at edu.pitt.dbmi.causal.cmd.tetrad.TetradRunner.lambda$runSearch$3(TetradRunner.java:203)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at edu.pitt.dbmi.causal.cmd.tetrad.TetradRunner.runSearch(TetradRunner.java:202)
	at edu.pitt.dbmi.causal.cmd.tetrad.TetradRunner.runAlgorithm(TetradRunner.java:119)
	at edu.pitt.dbmi.causal.cmd.CausalCmdApplication.runTetrad(CausalCmdApplication.java:149)
	at edu.pitt.dbmi.causal.cmd.CausalCmdApplication.main(CausalCmdApplication.java:113)
```

[tetrad_data_v2.temp.zip](https://github.com/cmu-phil/tetrad/files/9391035/tetrad_data_v2.temp.zip)

**Comment by jdramsey** [comment]
Hmm... I'm not getting that, but it's extraordinarily slow. Try the DG score instead.

**Comment by jdramsey** [comment]
(sorry I've been working in the GUI lately, that might have influenced it...)

**Comment by jdramsey** [comment]
@lockmatrix GRaSP is in much better shape now in the newly released 7.1.3-1. We'll have the corresponding Causal Command 1.5.0 out soon, so you can try this again. If it fails, though please make a new issue just for the GRaSP problem. Thanx!

**Comment by lockmatrix** [comment]
Thanks, but I'm not working on that project anymore.

**Comment by jdramsey** [comment]
@lockmatrix Oh, thanks for letting me know!
