### ISSUE TITLE
IndTestProbabilistic: Array Index Out of Bound

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#1489]
I got ArrayIndexOutOfBoundsException when running RFCI using IndTestProbabilistic:

```java
java.lang.ArrayIndexOutOfBoundsException: 70
	at edu.pitt.dbmi.algo.bayesian.constraint.inference.BCInference.probConstraint(BCInference.java:219)
	at edu.cmu.tetrad.search.IndTestProbabilistic.probConstraint(IndTestProbabilistic.java:232)
	at edu.cmu.tetrad.search.IndTestProbabilistic.checkIndependence(IndTestProbabilistic.java:193)
	at edu.cmu.tetrad.search.IndTestProbabilistic.checkIndependence(IndTestProbabilistic.java:146)
	at edu.cmu.tetrad.search.Rfci.setMinSepSet(Rfci.java:459)
	at edu.cmu.tetrad.search.Rfci.ruleR0_RFCI(Rfci.java:299)
	at edu.cmu.tetrad.search.Rfci.search(Rfci.java:200)
	at edu.cmu.tetrad.search.Rfci.search(Rfci.java:171)
	at edu.cmu.tetrad.search.Rfci.search(Rfci.java:167)
	at edu.pitt.dbmi.pag.sampling.rfci.PagSamplingRfci$RfciSearchTask.call(PagSamplingRfci.java:189)
	at edu.pitt.dbmi.pag.sampling.rfci.PagSamplingRfci$RfciSearchTask.call(PagSamplingRfci.java:170)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

```

**Comment by jdramsey** [comment]
@kvb2univpitt This can be closed now right?

**Comment by kvb2univpitt** [comment]
@jdramsey Yes.  I'll close it.  Thanks.
