### ISSUE TITLE
Unable to Launch Job Remotely Via the Latest REST API

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#364]
I got the following error:

```java
Executing request POST http://localhost:9001/ccd-api/1/jobs/fgesc HTTP/1.1
{"timestamp":1481468117863,"status":405,"error":"Method Not Allowed","message":"HTTP 405 Method Not Allowed","path":"/1/jobs/fgesc"}
org.json.JSONException: JSONObject["id"] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at org.json.JSONObject.getLong(JSONObject.java:655)
	at edu.pitt.dbmi.ccd.rest.client.util.JsonUtils.parseJSONObjectToJobInfo(JsonUtils.java:155)
	at edu.pitt.dbmi.ccd.rest.client.util.JsonUtils.parseJSONObjectToJobInfo(JsonUtils.java:151)
	at edu.pitt.dbmi.ccd.rest.client.service.jobqueue.JobQueueService.addToRemoteQueue(JobQueueService.java:59)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.doRemoteCompute(GeneralAlgorithmEditor.java:929)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.access$1000(GeneralAlgorithmEditor.java:103)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor$7.watch(GeneralAlgorithmEditor.java:528)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:167)
	at java.lang.Thread.run(Thread.java:745)

```
The latest REST API capitalized FGES and GFCI in the paths.  It seems to be case-sensitivity problem.

**Comment by chirayukong** [comment]
Fixed them on causal-tetrad-rest-client and tested on my mac. :-)
