### ISSUE TITLE
causal-cmd output directory handling not creating absolute paths?

### ISSUE THREAD

**Issue by harryhoch** [cmu-phil/tetrad#381]
I'm trying to run causal-cmd with an absolute path for --output.  E.g.:

java -Xmx1G -jar /home/harryh/causal-cmd-6.1.0-jar-with-dependencies.jar --algorithm FGESc --data /pylon1/bi4s84p/harryh/pam50-basal-continuous.csv --exclude-variables basal-output_zero_variance.txt --output /pylon1/bi4s84p/harryh/basal-output

however, I get an nio exception that looks like it might be looking for a relative path:

java.nio.file.NoSuchFileException: ./pylon1/bi4s84p/harryh/basal-output.txt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at edu.cmu.tetrad.cli.AbstractAlgorithmCli.run(AbstractAlgorithmCli.java:132)
	at edu.cmu.tetrad.cli.CausalCmdApplication.runAlgorithm(CausalCmdApplication.java:134)
	at edu.cmu.tetrad.cli.CausalCmdApplication.main(CausalCmdApplication.java:180)

when I run with a relative path - it works fine. e.g.

java -Xmx1G -jar /home/harryh/causal-cmd-6.1.0-jar-with-dependencies.jar --algorithm FGESc --data /pylon1/bi4s84p/harryh/pam50-basal-continuous.csv --exclude-variables basal-output_zero_variance.txt --output basal-output

**Comment by jdramsey** [comment]
@harryhoch Was this fixed? Can I close the issue?

**Comment by harryhoch** [comment]
Nope. not fixed. I just pulled causal-cmd-0.2.0 and built it, and it now fails silently without writing any output.

**Comment by espinoj** [comment]
moving this causal cmd project
