### ISSUE TITLE
FGES Discrete Cannot Handle Missing Values

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#474]
Got the follow error when run FGES discrete on discrete data with missing values:

````
Caused by: java.lang.ArrayIndexOutOfBoundsException: -99
	at edu.cmu.tetrad.search.BDeuScore.localScore(BDeuScore.java:135)
	at edu.cmu.tetrad.search.BDeuScore.localScore(BDeuScore.java:186)
	at edu.cmu.tetrad.search.BDeuScore.localScoreDiff(BDeuScore.java:174)
	at edu.cmu.tetrad.search.Fges$NodeTaskEmptyGraph.compute(Fges.java:572)
	at edu.cmu.tetrad.search.Fges$NodeTaskEmptyGraph.compute(Fges.java:529)
````

**Comment by jdramsey** [comment]
We need to get Greg's input on this, I think. My plan, which I will code up now, is to make the various discrete and mixed scores simply skip rows in the data for each particular scoring operation where there is a missing value. This is on part with what PC does. Unfortunately it's suboptimal. It would be better for the user to figure out what they want to do with the missing values. But it's a solution.

**Comment by jdramsey** [comment]
This is fixed for BDeuScore, BicScore, and ConditionalGaussianScore.
