### ISSUE TITLE
Uncaught NPE in algorithm chooser

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#535]
When highlighting an algorithm NPE is generated in console:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.getScoreWrapper(GeneralAlgorithmEditor.java:1373)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.getAlgorithmFromInterface(GeneralAlgorithmEditor.java:1335)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.setAlgorithm(GeneralAlgorithmEditor.java:1454)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.lambda$createAlgoChooserPanel$6(GeneralAlgorithmEditor.java:490)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor$$Lambda$25/1929611896.valueChanged(Unknown Source)

**Comment by chirayukong** [comment]
<img width="955" alt="screen shot 2017-10-19 at 5 30 12 pm" src="https://user-images.githubusercontent.com/4652250/31795286-384a015e-b4f3-11e7-81f2-69ea1c96e17f.png">
I don't see any NPE on the list.

**Comment by chirayukong** [comment]
Also, I think the empty score wrapper problem was already fixed by @kvb2univpitt.
