### ISSUE TITLE
Tetrad GUI: Cannot Handle Empty List Of Scores and Tests

### ISSUE THREAD

**Issue by kvb2univpitt** [cmu-phil/tetrad#536]
After filtering out experiment scores and tests, the list of scores for mixed datatype is empty.  GeneralAlgorithmEditor doesn't seem to handle that well.

```java
java.lang.IllegalStateException: Could not construct editor
	at edu.cmu.tetradapp.app.TetradApplicationConfig$DefaultModelConfig.getEditorInstance(TetradApplicationConfig.java:551)
	at edu.cmu.tetradapp.app.SessionEditorNode.launchEditorVisit(SessionEditorNode.java:236)
	at edu.cmu.tetradapp.app.SessionEditorNode.access$100(SessionEditorNode.java:64)
	at edu.cmu.tetradapp.app.SessionEditorNode$2.watch(SessionEditorNode.java:209)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at edu.cmu.tetradapp.app.TetradApplicationConfig$DefaultModelConfig.getEditorInstance(TetradApplicationConfig.java:549)
	... 5 more
Caused by: java.lang.NullPointerException
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.getScoreWrapper(GeneralAlgorithmEditor.java:1373)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.getAlgorithmFromInterface(GeneralAlgorithmEditor.java:1335)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.setAlgorithm(GeneralAlgorithmEditor.java:1454)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.lambda$createAlgoChooserPanel$6(GeneralAlgorithmEditor.java:490)
	at javax.swing.JList.fireSelectionValueChanged(JList.java:1796)
	at javax.swing.JList$ListSelectionHandler.valueChanged(JList.java:1810)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.JList.setSelectedIndex(JList.java:2210)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.setDefaultSelectedAlgo(GeneralAlgorithmEditor.java:921)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.setSelection(GeneralAlgorithmEditor.java:910)
	at edu.cmu.tetradapp.editor.GeneralAlgorithmEditor.<init>(GeneralAlgorithmEditor.java:213)
	... 10 more

```

**Comment by kvb2univpitt** [comment]
Fixed.
