### ISSUE TITLE
Time Series simulation doesn't work after changing Type of Simulation Model

### ISSUE THREAD

**Issue by espinoj** [cmu-phil/tetrad#597]
Simulate a time series
Run a search
Change the Simulation Model in the simulate box
Exception
```
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:839)
	at java.util.Collections.max(Collections.java:729)
	at edu.cmu.tetrad.search.TimeSeriesUtils.getKnowledge(TimeSeriesUtils.java:714)
	at edu.cmu.tetrad.algcomparison.simulation.TimeSeriesSemSimulation.createData(TimeSeriesSemSimulation.java:47)
	at edu.cmu.tetradapp.editor.SimulationEditor$3$1.watch(SimulationEditor.java:155)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Exception in creating data. Check model setup or parameter settings.
	at edu.cmu.tetradapp.editor.SimulationEditor$3$1.watch(SimulationEditor.java:164)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-57" java.lang.IllegalArgumentException: Exception in creating data. Check model setup or parameter settings.
	at edu.cmu.tetradapp.editor.SimulationEditor$3$1.watch(SimulationEditor.java:164)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:839)
	at java.util.Collections.max(Collections.java:729)
	at edu.cmu.tetrad.search.TimeSeriesUtils.getKnowledge(TimeSeriesUtils.java:714)
	at edu.cmu.tetrad.algcomparison.simulation.TimeSeriesSemSimulation.createData(TimeSeriesSemSimulation.java:47)
	at edu.cmu.tetradapp.editor.SimulationEditor$3$1.watch(SimulationEditor.java:155)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Exception in creating data. Check model setup or parameter settings.
	at edu.cmu.tetradapp.editor.SimulationEditor$3$1.watch(SimulationEditor.java:164)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "Thread-59" java.lang.IllegalArgumentException: Exception in creating data. Check model setup or parameter settings.
	at edu.cmu.tetradapp.editor.SimulationEditor$3$1.watch(SimulationEditor.java:164)
	at edu.cmu.tetradapp.util.WatchedProcess$1.run(WatchedProcess.java:164)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by chirayukong** [comment]
[Fix issue 597](https://github.com/cmu-phil/tetrad/tree/fix-issue-597)
