### ISSUE TITLE
CCD helpdesk

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#845]
@jdramsey @espinoj 

From the helpdesk. A user got this error message while running the next analysis:

My overall goal is to identify genetic loci that cause worse disease outcomes in patient's with inflammatory bowel disease.  To do this I have ~1600 genetic loci that are characterized as 0 (no genetic variant), 1 (1 genetic variant-heterozygotes), 2 (2 genetic variants at that loci-homozygous), and 3 (data missing).  The outcomes are a mixture of continuous and discrete data including number of ED visits, number of hospitalizations, total medical costs, failure to respond to medications, number of surgeries, and a few more things for a total of 10 outcomes. 

In total I have approximately 800 patients (and therefore 800 rows) with the ~1600 genetic loci and 10 outcome variables (~1600 columns, input data attached).  I have setup two tiers (please see knowledge file) with the genetic sequences on top and the outcomes below.  In tier 1 I do not want analysis between genetic loci and have put a star in the knowledge file.

This is run in Causal-Web, using the default parameters. 

I guess the error comes from memory overload, but I was wondering if something could be deduced from the data about why the error comes.

Thanks.

 Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

at java.util.EnumMap.<init>(EnumMap.java:139)

at edu.pitt.dbmi.data.validation.ValidationResult.<init>(ValidationResult.java:43)

at edu.pitt.dbmi.data.validation.ValidationResult.<init>(ValidationResult.java:47)

at edu.pitt.dbmi.data.validation.tabular.MixedTabularDataFileValidation.validateData(MixedTabularDataFileValidation.java:378)

at edu.pitt.dbmi.data.validation.tabular.MixedTabularDataFileValidation.validateDataFromFile(MixedTabularDataFileValidation.java:71)

at edu.pitt.dbmi.data.validation.tabular.AbstractTabularDataValidation.validate(AbstractTabularDataValidation.java:62)

at edu.pitt.dbmi.causal.cmd.tetrad.TetradUtils.validateTabularData(TetradUtils.java:241)

at edu.pitt.dbmi.causal.cmd.tetrad.TetradUtils.validateDataModels(TetradUtils.java:154)

at edu.pitt.dbmi.causal.cmd.tetrad.TetradAlgorithmRunner.runAlgorithm(TetradAlgorithmRunner.java:63)

at edu.pitt.dbmi.causal.cmd.tetrad.TetradRunner.runTetrad(TetradRunner.java:67)

at edu.pitt.dbmi.causal.cmd.CausalCmdApplication.main(CausalCmdApplication.java:83)

**Comment by cabal-cmu** [comment]
For replication, I attached the files the user send.
[nfkbgt2TextHeaderSimplified2.txt](https://github.com/cmu-phil/tetrad/files/2134657/nfkbgt2TextHeaderSimplified2.txt)

[knowledge.prior.txt](https://github.com/cmu-phil/tetrad/files/2134658/knowledge.prior.txt)

**Comment by yuanzhou** [comment]
@kvb2univpitt sure thing. I've switched to a more powerful EC2 instance for running Causal-web on AWS before the short course, we can increase the memory within CMD for sure.

**Comment by cabal-cmu** [comment]
@kvb2univpitt @yuanzhou can you let me know when this memory fix is done, so I can answer back the user about his problem.

Thanks.

**Comment by kvb2univpitt** [comment]
@cabal-cmu It's done.  Memory has been increased.  The user must set the amount of memory (GB) given to the algorithm by setting the the advanced options for Java JVM, as shown in the screenshot below:
![screenshot from 2018-06-29 10-54-14](https://user-images.githubusercontent.com/10729309/42099394-4ff5c324-7b8b-11e8-9ee2-369e54d0c118.png)

If 4GB is not enough, the user can increase it up to 8,10, and so forth.

**Comment by yuanzhou** [comment]
FYI, don't go too big memory since the AWS EC2 instance running Causal-Web has a limit of 16G currently.

**Comment by rubencmu** [comment]
?Thanks. I will notify the user.


Ruben


________________________________

**Comment by espinoj** [comment]
closing as this is definitely an out of memory condition that we have addressed
