### ISSUE TITLE
Web app error message

### ISSUE THREAD

**Issue by cabal-cmu** [cmu-phil/tetrad#863]
HI, from the CCD helpdesk,  a user got this error while running the web app

Jul 19, 2018 1:54:01 PM java.util.prefs.FileSystemPreferences$6 run

WARNING: Prefs file removed in background /home/ec2-user/.java/.userPrefs/prefs.xml

Exception in thread "main" java.lang.NullPointerException: Cutoffs must be in nondecreasing order.

at edu.cmu.tetrad.data.Discretizer.discretize(Discretizer.java:333)

at edu.cmu.tetrad.search.ConditionalGaussianLikelihood.useErsatzVariables(ConditionalGaussianLikelihood.java:176)

at edu.cmu.tetrad.search.ConditionalGaussianLikelihood.<init>(ConditionalGaussianLikelihood.java:138)

at edu.cmu.tetrad.search.ConditionalGaussianScore.<init>(ConditionalGaussianScore.java:60)

at edu.cmu.tetrad.algcomparison.score.ConditionalGaussianBicScore.getScore(ConditionalGaussianBicScore.java:32)

at edu.cmu.tetrad.algcomparison.algorithm.oracle.pattern.Fges.search(Fges.java:78)

at edu.pitt.dbmi.causal.cmd.tetrad.TetradAlgorithmRunner.runAlgorithm(TetradAlgorithmRunner.java:102)

at edu.pitt.dbmi.causal.cmd.tetrad.TetradRunner.runTetrad(TetradRunner.java:67)

at edu.pitt.dbmi.causal.cmd.CausalCmdApplication.main(CausalCmdApplication.java:83)

**Comment by yuanzhou** [comment]
Causal web is no longer supported or being publicly used.
